package com.company;
class Runable1 implements Runnable {
    public void run() { // I am in itelij idea I Can do this by ctrl + d
        System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");  System.out.println("The best coder");
        System.out.println("A");
    }
}
class Runable2 implements Runnable{
    public void run(){
        System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");  System.out.println("The best coder");
        System.out.println("B");
    }
}
public class Runableinterface {

    public static void main(String[] args) {
    Runable1 tt1 =new Runable1();
    Thread t1 = new Thread(tt1);
    Runable2 tt2 = new Runable2();
        Thread t2    = new Thread(tt2);
    t1.start();
    t2.start();

    }}
